### ISSUE TITLE
Doesn't work with Python 3.11

### ISSUE THREAD

**Issue by dkadioglu** [enen92/script.tubecast#75]
On the Libreelec Nightly 181122 TubeCast doesn't work anymore and errors out with:
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'getargspec' from 'inspect' (/usr/lib/python3.11/inspect.pyc)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.tubecast/main.py", line 2, in <module>
                                                       from resources.lib import service
                                                     File "/storage/.kodi/addons/script.tubecast/resources/lib/service.py", line 5, in <module>
                                                       from resources.lib.tubecast.chromecast import Chromecast
                                                     File "/storage/.kodi/addons/script.tubecast/resources/lib/tubecast/chromecast.py", line 12, in <module>
                                                       from resources.lib.tubecast.dial import app
                                                     File "/storage/.kodi/addons/script.tubecast/resources/lib/tubecast/dial.py", line 2, in <module>
                                                       from bottle import Bottle, request, response
                                                     File "/storage/.kodi/addons/script.module.bottle/lib/bottle.py", line 44, in <module>
                                                       from inspect import getargspec
                                                   ImportError: cannot import name 'getargspec' from 'inspect' (/usr/lib/python3.11/inspect.pyc)
                                                   -->End of Python script error report<--
```

This seems to happen because of the recent switch to Python 3.11.
I found this which might be related and help:
https://docs.python.org/3.11/whatsnew/3.11.html#removed

**Comment by enen92** [comment]
Hey @dkadioglu your bug report looks unrelated. Tubecast doesn't use any of those modules, the stack trace you posted is for script.service.kodi.callbacks...

**Comment by dkadioglu** [comment]
Ups, sorry, I mixed up the stack traces! Edited the report accordingly. I am very sorry!

**Comment by pretoriano80** [comment]
I can confirm this on both LibreELEC Nightly and my FireTV 4k (Android 7) with Kodi 20.0 beta 1.

In the logs i got the exactly same error as the OP.

**Comment by enen92** [comment]
Looks like bottle needs an update on the Kodi repo

**Comment by enen92** [comment]
fixed in the PR above
